MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [512, 512, 512, 128, 128, 64]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[75, 75], [38, 38], [19, 19], [10, 10], [5, 5], [3, 3]]
        MIN_SIZES: [[30, 30], [60, 60], [156, 156], [252, 252], [348, 348], [444, 444]]
        MAX_SIZES: [[60, 60], [156, 156], [252, 252], [348, 348], [444, 444], [540, 540]]
        #MIN_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
        #MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]] 
INPUT:
    IMAGE_SIZE: [600, 600]
    #ImageNet normalization
    #PIXEL_MEAN: [0.485, 0.456, 0.406]
    #PIXEL_STD: [0.229, 0.224, 0.225]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 50000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
    AMSGRAD: True
    WEIGHT_DECAY: 5e-4
EVAL_STEP: 1500
MODEL_SAVE_STEP: 5000
OUTPUT_DIR: 'outputs/rdd2020_2'
DATASET_DIR: "datasets"