MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [64, 128, 256, 128, 128, 64, 64]
        INPUT_CHANNELS: 3
    PRIORS:
      FEATURE_MAPS: [[75,125], [63, 38], [32, 19], [17, 10], [8, 5], [5, 3], [2, 1]]
      STRIDES: [[4,4], [8, 8], [16, 16], [32, 32], [64, 64], [128, 128], [512, 512]]
      MIN_SIZES: [[50,30], [115,69], [180,108], [245,147], [310,186], [375,225], [440,264]]
      MAX_SIZES: [[115,69], [180,108], [245,147], [310,186], [375,225], [440,264], [525,315]]
      ASPECT_RATIOS: [[2], [2], [2, 3], [2, 3], [2, 3], [2], [2]]
      BOXES_PER_LOCATION: [2, 4, 6, 6, 6, 4, 4]
INPUT:
    IMAGE_SIZE: [500, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
    AMSGRAD: True
    WEIGHT_DECAY: 5e-4
EVAL_STEP: 1500
MODEL_SAVE_STEP: 5000
OUTPUT_DIR: 'outputs/rdd2020'
DATASET_DIR: "datasets"
